version: '3.8'

services:
  # Backend: Modular FastAPI App
  aml-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aml-fastapi-backend
    environment:
      # Use host.docker.internal to bridge to the ETL age_db container running on 5433
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5433/age_prod_01
      ENV: production
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - aml-network


  # 3. Frontend: Next.js App
  aml-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aml-nextjs-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - aml-backend
    restart: unless-stopped
    networks:
      - aml-network

volumes:
  aml_pgdata:

networks:
  aml-network:
    driver: bridge
