version: '3.8'

services:
  age_db:
    image: apache/age
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: age_prod_01
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - age_pg_data:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/00_init_schema.sql
      - ../aml_platform/backend/init_scripts/01_rbac_initialization.sql:/docker-entrypoint-initdb.d/01_rbac_initialization.sql
      - ../aml_platform/backend/init_scripts/02_audit_tamper_evidence.sql:/docker-entrypoint-initdb.d/02_audit_tamper_evidence.sql
      - ../aml_platform/backend/init_scripts/03_keycloak_initialization.sql:/docker-entrypoint-initdb.d/03_keycloak_initialization.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "age_prod_01" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dagster_etl:
    build:
      context: .
    restart: always
    env_file:
      # <--- Add this
      - .env # <--- Add this
    environment:
      DAGSTER_HOME: /opt/dagster/app
      POSTGRES_URI: postgresql://postgres:password@age_db:5432/age_prod_01
    ports:
      - "3001:3000"
    volumes:
      - .:/opt/dagster/app
      - ../input_data:/opt/dagster/input_data
    depends_on:
      age_db:
        condition: service_healthy
    command: dagster dev -h 0.0.0.0 -p 3000

volumes:
  age_pg_data:
